# Generated by Django 5.1.1 on 2024-09-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quackpack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='mob',
            field=models.IntegerField(),
        ),
    ]
