# Generated by Django 5.1.1 on 2024-09-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quackpack', '0003_remove_students_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardens',
            name='hostel',
            field=models.CharField(default='Ladies', max_length=10),
        ),
    ]
