# Generated by Django 5.1.1 on 2024-09-21 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quackpack', '0004_wardens_hostel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardens',
            name='mob',
        ),
        migrations.RemoveField(
            model_name='wardens',
            name='regno',
        ),
    ]
